export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCTS_REQUEST = 'GET_PRODUCTS_REQUEST';

export const GET_PRODUCT = 'GET_PRODUCT';
export const GET_PRODUCT_REQUEST = 'GET_PRODUCT_REQUEST';
